### ISSUE TITLE
能在一些公开数据集上对比一下监督学习的效果吗

### ISSUE THREAD

**Issue by zlszhonglongshen** [taishan1994/ChatSA#1]
看看和其他算法再一些公开数据集上的表现？比如paddlenlp的uie-sent

**Comment by taishan1994** [comment]
> 看看和其他算法再一些公开数据集上的表现？比如paddlenlp的uie-sent

加了一下对比的结果，可以看下。

**Comment by zlszhonglongshen** [comment]
> > 看看和其他算法再一些公开数据集上的表现？比如paddlenlp的uie-sent
> 
> 加了一下对比的结果，可以看下。

强

**Comment by zlszhonglongshen** [comment]
感觉上 ，gpt要比百度的在观点提取上要好

**Comment by taishan1994** [comment]
> 感觉上 ，gpt要比百度的在观点提取上要好

提取的更全面。

**Comment by xxllp** [comment]
有具体的评估指标看下嘛，而且如果没有gpt，是否可以用一些开源方案呢

**Comment by taishan1994** [comment]
> 有具体的评估指标看下嘛，而且如果没有gpt，是否可以用一些开源方案呢

没有评价指标，事实上只要有类似于ChatGPT的大模型，都可以尝试下用这种方法。

**Comment by xxllp** [comment]
好的
